### ISSUE TITLE
Next should have major's commits

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2432]
Here's a todolist for getting `next` uptodoate:

- [x] a5afa20 Add first class support for Backbone.Radio in Mn.Object
- [x] c63b584 Add missing files/tests and remove unused/non-existent tests from specRunner
- [x] 8897fb6 doc(behavior): add some doc + ui section missing
- [x] 2bf99cf  feat(behavior): override behavior ui with view ui
- [x] ~~05a5d88 Simplify travis file~~
- [x] 53d684a Make sure before:render is triggered before emptying regions.
- [x] ~~a9007c4 Add lodash 3.1 to matrix~~
- [x] ~~16cc6a9 Add lodash to test matrix~~
- [x] 19b73f0 delegateEntityEvents
- [x] 13757c7 Remove Marionette.Deferred
- [x] a412f17 Kill callbacks
- [x] 57bf2ad Delete Marionette.Module
- [x] fb618f3 Rename ItemView to be View.
- [x] 3a7851e Remove Controller.
- [x] 552d728 Remove Regions from Application.
- [x] 8a11d6f Remove Channels from the Application. Remove Wreqr as a dependency.
- [x] 5b617d0 Merge LayoutView into ItemView.
- [x] 8f3e721 childEvents => childViewEvents
- [x] 63e83dd Rename Marionette.View to be Marionette.AbstractView.
- [x] f14b7eb Refactor serializeData to no longer use toJSON.

**Comment by jasonLaster** [comment]
Here's a todolist for getting `next` uptodoate:



- [ ] 05a5d88 Simplify travis file
- [ ] 40d964a Merge pull request #2314 from scottaj/fire-before-render-before-emptying-regions
- [ ] 77c3f56 Merge pull request #2241 from paulfalgout/refactor/delegateEntityEvents
- [ ] 53d684a Make sure before:render is triggered before emptying regions.
- [ ] a9007c4 Add lodash 3.1 to matrix
- [ ] 16cc6a9 Add lodash to test matrix
- [ ] 19b73f0 delegateEntityEvents
- [ ] c452f7d Merge pull request #2288 from marionettejs/rename-itemview
- [ ] 94eb855 Merge pull request #2256 from marionettejs/sjs/kill-calbacks
- [ ] 13757c7 Remove Marionette.Deferred
- [ ] a412f17 Kill callbacks
- [ ] 57bf2ad Delete Marionette.Module
- [ ] fb618f3 Rename ItemView to be View.
- [ ] 3c612cd Merge pull request #2282 from marionettejs/bye-controller
- [ ] 3a7851e Remove Controller.
- [ ] 2089064 Merge pull request #2270 from marionettejs/bye-app-regions
- [ ] 552d728 Remove Regions from Application.
- [ ] b9bade8 Merge pull request #2269 from marionettejs/bye-app-channel
- [ ] 8a11d6f Remove Channels from the Application. Remove Wreqr as a dependency.
- [ ] 9dac0d9 Merge pull request #2253 from marionettejs/layout-view
- [ ] 5b617d0 Merge LayoutView into ItemView.
- [ ] 8f3e721 childEvents => childViewEvents
- [ ] 63e83dd Rename Marionette.View to be Marionette.AbstractView.
- [ ] f14b7eb Refactor serializeData to no longer use toJSON.
- [ ] b724fa3 [child_view_attribute_renamed] fixing issue #2121
- [ ] 4b0fade Merge pull request #2258 from marionettejs/sjs/add-underscore-1-7
- [ ] 7ef8951 Add grid tests for underscore 1.7
- [ ] f0684ff Merge pull request #2141 from megawac/layout-view-cleanup
- [ ] 36bc105 Fix #2134; LayoutView should remove its element before destroying child regions
- [ ] 83c3026 Merge pull request #2240 from paulfalgout/collectionview-before-show
- [ ] da9578b Merge pull request #2243 from paulfalgout/fix/docs
- [ ] 3649800 Doc linking fixes
- [ ] d0013da Add before:show event to ChildView when added after show
- [ ] 964c316 Merge pull request #2234 from jridgewell/patch-1
- [ ] 6835f9e Use call when there are no params
- [ ] e866575 Add LayoutView shortcut methods
- [ ] f628b3b listenTo doesn't have a fourth argument.
- [ ] 3eff57c Add template-cache options.
- [ ] e7e1036 Support @ui selectors in region definition objects for LayoutView.
- [ ] 4cc0096 Enable passing preventDestroy to region.empty.
- [ ] 403f605 Allow custom sort comparator for CollectionView
- [ ] 55fa7c2 isRendered should be true for a itemView after render with no template set
- [ ] a2f7341 Add `isRendered` property to Views- [ ]

**Comment by paulfalgout** [comment]
So is this still a thing?

**Comment by jasonLaster** [comment]
Big time. We need to cherry pick these remaining commits. Team effort :)

**Comment by paulfalgout** [comment]
Ah so I see a reference to `next` in the 2nd comment, perhaps this issue just needs to be renamed?

**Comment by jasonLaster** [comment]
Updated. The issue could be better titled and have more details, but alas I'm on my phone

**Comment by paulfalgout** [comment]
https://github.com/marionettejs/backbone.marionette/pull/2476  Rename ItemView to be View.

Needs some :eyes:

Also noticed that docs and yaml were not merged in: Merge LayoutView into ItemView.  :sob:

**Comment by jasonLaster** [comment]
Oh no, did I drop the docs?

**Comment by paulfalgout** [comment]
What about:
2bf99cf  feat(behavior): override behavior ui with view ui
8897fb6 doc(behavior): add some doc + ui section missing
c63b584 Add missing files/tests and remove unused/non-existent tests from specRunner
a5afa20 Add first class support for Backbone.Radio in Mn.Object

**Comment by paulfalgout** [comment]
Someone more intimately aware of the behavior stuff hint: @jasonLaster might need to look at the next one.. it is possible we're still missing something prior to this commit..  and `viewUI` is not defined at all in the current `next`

**Comment by paulfalgout** [comment]
I traced the diff back to here:  https://github.com/marionettejs/backbone.marionette/pull/2344/files#diff-6e430c44cbb3a1d898cce330e7bfd4d5R23

I believe I know how to proceed.

**Comment by paulfalgout** [comment]
Done :Boom: :bomb: :fireworks: 

:eyes: sanity check please  @marionettejs/marionette-core
