### ISSUE TITLE
Create Marionette Radio docs 

### ISSUE THREAD

**Issue by jasonLaster** [marionettejs/backbone.marionette#2647]
Currently, people have to go to Marionette Radio to read the readme to understand how to use the lib.

Lets have some documention in Marionette for Radio. This is especially important w/ `next` as we introduce some helpful APIs on top of Radio.

The docs should have the methods that are available, but also useful Eventing patterns that are common best practices

## Todo List

* [x] Document channels
* [x] Document Request/Reply
* [x] Document Events
* [x] Clarify difference in when to use Events vs Request
* [x] Document Radio Integration with Marionette

**Comment by scott-w** [comment]
Things to do for this:

* [ ] Document channels
* [ ] Document Request/Reply
* [ ] Document Events
* [ ] Clarify difference in when to use Events vs Request
* [ ] Document Radio Integration with Marionette

**Comment by scott-w** [comment]
I'll close this for now. We can give them another run through later.
