### ISSUE TITLE
New docs for View

### ISSUE THREAD

**Issue by scott-w** [marionettejs/backbone.marionette#2920]
We need to document the `View` class as the basic view completely replaces `ItemView` and `LayoutView`.

## Todo List

* [x] Write the `View` documentation containing:
  * [x] Templates and rendering
    * [x] Rendering a model
    * [x] Rendering a collection
    * [x] Link to advanced rendering doc
  * [x] Regions
  * [x] Organising views (e.g. ui)
  * [x] Events
    * [x] Model and Collection events
    * [x] Listening to child events
    * [x] Link through to detailed event doc
* [x] Remove references to `AbstractView`

If anyone has any extra suggestions, either add them to the list or comment and I'll add them.

## Replaces

* #2477

**Comment by vernondegoede** [comment]
I definitely would like to document these subjects.

**Comment by ahumphreys87** [comment]
great @vernondegoede, help is greatly appreciated

**Comment by vernondegoede** [comment]
@scott-w Let's have a Gitter chat tomorrow on how to start :)

**Comment by curzonj** [comment]
When reading the v3 View docs, I would have liked to see the events that regions would fire on the view in the view docs in addition to the region docs.

**Comment by scott-w** [comment]
Does that include things like the `showChildView('region', view)` lifecycle?

**Comment by paulfalgout** [comment]
We need to go through every file and consider how to remove references to `AbstractView` seeing as it doesn't exist..  now the view's are composed with mixins instead of extending from a shared view class.

**Comment by scott-w** [comment]
I've checked the last items off the above list against the documentation and this can be closed now.

**Comment by paulfalgout** [comment]
I'm not 100% sure of https://github.com/marionettejs/backbone.marionette/blob/next/docs/marionette.view.md#region-availability

It says:
> Any defined regions within a View will be available to the View or any calling code immediately after instantiating the View

which is kind of true.  If the view has DOM (ie: was already there and therefore pre-rendered) then there are regions that will work.. 
Even without DOM the regions are _available_ (like you could setup listeners) but.. they can't be used to show a child if the view isn't rendered.. so the next sentence is confusing:

> This allows a View to be attached to an existing DOM element in an HTML page, without the need to call a render method or anything else, to create the regions.

The next paragraph clarifies, but somehow flipping this around and starting with the common case.. the view has no DOM.. might be clearer..
