### ISSUE TITLE
CollectionView Documentation

### ISSUE THREAD

**Issue by scott-w** [marionettejs/backbone.marionette#3052]
The documentation for `CollectionView` needs to be updated in line with Marionette 3 standards.

## Todo

* [x] Outline `CollectionView` features
  * [x] How to show child views
  * [x] Empty view behaviour
  * [x] Example rendering for different views
* [x] Document `CollectionView` specific events
  * [x] Move Collection View events into the `events.md` file
  * [x] Create a separate set of files for View Lifecycle events
* [x] Separate in-depth rendering topics
  * [x] Build/add/render child views
  * [x] Managing child views (the Babysitter docs)
  * [x] Sorting and filtering the collection

**Comment by paulfalgout** [comment]
https://github.com/marionettejs/backbone.marionette/issues/3051

**Comment by scott-w** [comment]
I'm just looking this over and the `marionette.collectionview.md` doc is pretty long. I'm thinking we need to decide on a base set of functionality to document and pull the more advanced topics into their own section.

**Comment by ahumphreys87** [comment]
@scott-w I agree, cover common use cases and maybe just mention other functionality with links to the associated docs for it

**Comment by ahumphreys87** [comment]
Maybe, simple rendering and auto re-rendering, rendering a table (with a layout), sorting/filtering and reordering. Thoughts?

**Comment by paulfalgout** [comment]
@scott-w the events moving seems reasonable.  The rendering at the bottom could possibly be standalone as well.. I don't really know what would be advanced topics?  There are some things people will never touch.. _maybe_ sorting/filtering is more like secondary functionality.. it's pretty hard to break up the API reasonably in my opinion. :-/

**Comment by denar90** [comment]
Agree with you guys. I also noticed that we have some example of rendering tables using v2 and v3, should this section also be moved (e.g. upgrade guide) ?

**Comment by scott-w** [comment]
Good stuff, I'll update the description here.

**Comment by denar90** [comment]
Updated description due to #3117

**Comment by jonas-db** [comment]
Might be relevant to put into the documentation?https://github.com/marionettejs/backbone.marionette/issues/458#issuecomment-241187938

**Comment by paulfalgout** [comment]
@jonas-db https://github.com/marionettejs/backbone.marionette/blob/v3.0.0-pre.5/docs/marionette.collectionview.md#tables-using-marionette-3
