### ISSUE TITLE
Feature idea: Marionette.Behavior

### ISSUE THREAD

**Issue by samccone** [marionettejs/backbone.marionette#869]
### todo
- [x] proxy all view events
- [x] proxy model events
- [x] proxy collection events
- [x] expose listenTo
- [x] add a dedicated UI hash
- [x] add a dedicated events hash

A composable set of UI specific interactions that can be mixed into an arbitrary number of views.

``` coffeescript
    class Foo extends new Marionette.ItemView
        behaviors: [
            App.Behaviors.Tooltip,
                        # also can be defined with options
            {
                behavior: App.Behaviors.Draggable,
                options: {maxLength: 200}
            }
        ]
```

Behaviors are executed in the order that they are defined in the behaviors array.
Behavior setup takes optional `options` to customize any behavior

---

Allows for the separation of single interaction points into small non-coupled widgets.

```
# A behavior has a limited number of hooks into a views render/show. 
# This will limit their use and hopefully prevent their abuse.
```

``` coffeescript
    class Tooltip extends Marionette.Behavior
        # default options can be defined and are merged with the passed options
        defaultOptions:
          position: "top"
          animation: true

        onShow: ->
        onRender: ->
        onDomRefresh: ->
            @view.$('[title]').tooltip(@options)
        onClose: ->
        modelEvents: ->
        collectionEvents: ->
```
